server:
  port: 8080
  servlet:
    context-path: /

spring:

  application:
    name: '@project.artifactId@'
    version: '@project.version@'

  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

info:
  api:
    title: Stoom Store Test
    description: Stoom Store
    version: 1
    contact:
      name: Stoom
      url: www.stoom.com.br

management:
  endpoints:
    web:
      exposure.include: "health, info, metrics"
      base-path: /
      path-mapping:
        health: /healthcheck
  endpoint.health.showDetails: always